In [2]:
import numpy as np
import pandas as pd
import pickle
from collections import namedtuple
from sklearn.preprocessing import StandardScaler
from IPython.display import display, HTML
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression
from sklearn.svm import SVR,LinearSVR,NuSVR
from sklearn.kernel_ridge import KernelRidge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor,RandomForestRegressor,ExtraTreesRegressor,AdaBoostRegressor
from sklearn.feature_selection import RFECV
from sklearn.metrics import r2_score,make_scorer
from sklearn.model_selection import TimeSeriesSplit
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import (RBF, Matern, RationalQuadratic,
                                              ExpSineSquared, DotProduct,
                                              ConstantKernel)

Módulo 1 – Agrupamento - Questão 1
Considerando os dados do arquivo agrupamento_Q1.csv, execute o algoritmo K-means com 10 iterações tendo como posição inicial dos centroides de cada cluster as K primeiras linhas do arquivo agrup_centroides_Q1.csv. Por exemplo, para executar o algoritmo com 3 clusters considere os centroides determinados pelas 3 primeiras linhas do arquivo. 

Qual a quantidade ideal de clusters?
Qual o posicionamento final dos centroides do caso ideal

In [7]:
import random
random.seed(42)

In [8]:
df_agrupamento_Q1=pd.read_csv('raw_data/agrupamento_Q1.csv')
df_agrup_centroides_Q1=pd.read_csv('raw_data/agrup_centroides_Q1.csv')

In [21]:
df_agrupamento_Q1.shape

(1000, 4)

In [28]:
df_agrup_centroides_Q1.shape

(12, 6)

In [12]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score

df_agrup_centroides_Q1['lineas']=df_agrup_centroides_Q1['Unnamed: 0']
df_agrup_centroides_Q1.head()

   Unnamed: 0        X1        X2        X3        X4  lineas
0           1  1.488531 -0.430586  0.208942  0.018485       1
1           2  0.149391  1.549535  0.219688  0.917854       2
2           3  1.276714  0.844500  1.211906 -0.494781       3
3           4 -0.224172 -0.265252  1.004367 -0.209741       4
4           5  0.059576  0.946101  1.114006  0.401051       5

In [17]:
ndarray=df_agrup_centroides_Q1[:3][['X1','X2','X3','X4']]

In [19]:
kmeans = KMeans(n_clusters=3, init=ndarray,n_jobs=10).fit(df_agrupamento_Q1)

/Users/JR/anaconda3/envs/pyfinance/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:896: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)

In [20]:
kmeans.cluster_centers_

array([[ 1.01324094,  0.00102788, -0.00714053,  0.53264751],
       [ 0.00395699,  0.01094492,  0.01261755, -0.02089099],
       [ 0.99299277,  0.50426747,  0.98336064, -0.00245021]])

In [38]:
from sklearn.metrics import silhouette_samples, silhouette_score

score=-1
for k in range(2,13):
    ndarray=df_agrup_centroides_Q1[:k][['X1','X2','X3','X4']]
   
    kmeans = KMeans(n_clusters=k, init=ndarray,n_jobs=10).fit(df_agrupamento_Q1)
    preds=kmeans.predict(df_agrupamento_Q1)
    score_aux = silhouette_score(df_agrupamento_Q1, preds)
    print(k)
    print(score_aux) 
    if score_aux>score:
        kscore=k
        score=score_aux
        centers=kmeans.cluster_centers_

/Users/JR/anaconda3/envs/pyfinance/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:896: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)

2
0.377699689463
3
0.431186372403
4
0.436743673981
5
0.487012145843
6
0.413374709425
7
0.418517692725
8
0.36463504692
9
0.363606367842
10
0.364025472005
11
0.303785931069
12
0.25791455228

In [39]:
score

0.48701214584287539

In [41]:
kscore

5

In [43]:
centers

array([[  1.00809727e+00,   5.65625680e-03,  -6.05882233e-03,
          2.93292716e-02],
       [  9.95561737e-01,   6.26153151e-04,  -7.80409753e-03,
          1.00152120e+00],
       [  9.95952697e-01,   6.46273222e-03,   9.99718008e-01,
          3.14721258e-03],
       [ -3.47147275e-02,   1.63162909e-02,   1.04264751e-02,
         -1.62407503e-02],
       [  9.90740088e-01,   9.93047773e-01,   9.69936615e-01,
         -4.06482259e-03]])

In [42]:
kmeans.cluster_centers_

array([[ 0.94754123, -0.08958238,  0.0436254 ,  1.07128   ],
       [ 1.08190462,  0.15766972, -0.09359624,  0.86384912],
       [ 1.13598286,  0.92104376,  0.83636842, -0.03829049],
       [ 0.89010141, -0.21648325,  1.13047778, -0.00657484],
       [ 0.87884443,  1.12645292,  0.9355797 , -0.18577502],
       [-0.03471473,  0.01631629,  0.01042648, -0.01624075],
       [ 0.96375046,  0.97218281,  1.10255802,  0.16230573],
       [ 1.2631246 ,  0.01485649,  1.00650433,  0.03874813],
       [ 0.85047713,  0.14765082,  1.01580974,  0.17336243],
       [ 0.92358238,  0.15281721,  0.92326312, -0.19990605],
       [ 0.98982625, -0.04865149,  0.26521061,  0.05976391],
       [ 1.00524094,  0.02127295, -0.11981787,  0.00208597]])

Módulo 1 – Agrupamento - Questão 2
Assinale as alternativas com V ou F para Verdadeiro ou Falso respectivamente.
Atente para o fato que uma questão errada anula uma certa. Em caso de dúvidas deixe em branco.

A) O algoritmo K-means se baseia num processo iterativo que minimiza a soma das distâncias entre os centroides e os pontos dentro de cada agrupamento.

Algoritmos particionais são tipicamente mais eficientes computacionalmente do que algoritmos hierárquicos

F) Não é possível identificar outliers com algoritmos hierárquicos e, por este motivo, tais algoritmos requerem que os outliers sejam tratados em uma etapa necessária de pré-processamento.

O algoritmo GMM (Gaussian Mixture Models) presume que os dados a serem agrupados provém de uma distribuição unimodal.

O algoritmo K-median é mais sensível a outliers do que o algoritmo K-means.

C) Os centroides determinados pelo algoritmo K-means necessariamente pertencem ao conjunto de dados analisados


B) O algoritmo K-means é pouco sensível a inicialização dos centroides e resulta sempre nos mesmos agrupamentos.

In [44]:
Application to the law of cosines

Triangle with vector edges a and b, separated by angle θ.
Main article: Law of cosines
Given two vectors a and b separated by angle θ (see image right), they form a triangle with a third side c = a − b. The dot product of this with itself is:

{\displaystyle {\begin{aligned}\mathbf {c} \cdot \mathbf {c} &=(\mathbf {a} -\mathbf {b} )\cdot (\mathbf {a} -\mathbf {b} )\\&=\mathbf {a} \cdot \mathbf {a} -\mathbf {a} \cdot \mathbf {b} -\mathbf {b} \cdot \mathbf {a} +\mathbf {b} \cdot \mathbf {b} \\&=a^{2}-\mathbf {a} \cdot \mathbf {b} -\mathbf {a} \cdot \mathbf {b} +b^{2}\\&=a^{2}-2\mathbf {a} \cdot \mathbf {b} +b^{2}\\c^{2}&=a^{2}+b^{2}-2ab\cos \theta \\\end{aligned}}} {\begin{aligned}\mathbf {c} \cdot \mathbf {c} &=(\mathbf {a} -\mathbf {b} )\cdot (\mathbf {a} -\mathbf {b} )\\&=\mathbf {a} \cdot \mathbf {a} -\mathbf {a} \cdot \mathbf {b} -\mathbf {b} \cdot \mathbf {a} +\mathbf {b} \cdot \mathbf {b} \\&=a^{2}-\mathbf {a} \cdot \mathbf {b} -\mathbf {a} \cdot \mathbf {b} +b^{2}\\&=a^{2}-2\mathbf {a} \cdot \mathbf {b} +b^{2}\\c^{2}&=a^{2}+b^{2}-2ab\cos \theta \\\end{aligned}}

SyntaxError: invalid syntax (<ipython-input-44-db900d2aa4e1>, line 1)

Módulo 2 – Classificação - Questão 3
Considerando os dados presentes no arquivo classificacao_Q3.csv, treine o algoritmo Naive Bayes utilizando a metodologia de validação cruzada holdout (utilize para treino as 500 primeiras linhas e para validação as demais)
Qual o valor da acurácia a base de treino?
Qual o valor da acurácia média para as bases de validação?

In [45]:
df_classificacao_Q3=pd.read_csv('raw_data/classificacao_Q3.csv')

In [46]:
df_classificacao_Q3.head()

  Genero             Idade Escolaridade Profissao  Target
0      F  a - Ate 25 anos   Fundamental         b       0
1      M  a - Ate 25 anos         Medio         d       1
2      F  c - 36 a 45 anos  Fundamental         a       1
3      M  d - 46 a 55 anos  Fundamental         a       0
4      F  c - 36 a 45 anos  Fundamental         b       1

In [47]:
df_classificacao_Q3.shape

(1000, 5)

In [48]:
from sklearn.naive_bayes import GaussianNB

In [50]:
x=df_classificacao_Q3[['Genero','Idade','Escolaridade','Profissao']]

In [51]:
y=df_classificacao_Q3['Target']

In [52]:
y

0      0
1      1
2      1
3      0
4      1
5      0
6      0
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     0
29     1
      ..
970    1
971    1
972    1
973    1
974    1
975    1
976    1
977    1
978    0
979    1
980    1
981    1
982    1
983    1
984    0
985    1
986    1
987    1
988    0
989    1
990    1
991    1
992    1
993    1
994    0
995    0
996    1
997    1
998    1
999    1
Name: Target, Length: 1000, dtype: int64

In [53]:
x

    Genero             Idade   Escolaridade Profissao
0        F  a - Ate 25 anos     Fundamental         b
1        M  a - Ate 25 anos           Medio         d
2        F  c - 36 a 45 anos    Fundamental         a
3        M  d - 46 a 55 anos    Fundamental         a
4        F  c - 36 a 45 anos    Fundamental         b
5        F  b - 26 a 35 anos    Fundamental         b
6        F  a - Ate 25 anos     Fundamental         b
7        F  e - Mais 56 anos       Superior         b
8        F  a - Ate 25 anos        Superior         b
9        M  b - 26 a 35 anos    Fundamental         a
10       M  c - 36 a 45 anos    Fundamental         a
11       F  b - 26 a 35 anos    Fundamental         a
12       F  a - Ate 25 anos        Superior         b
13       F  b - 26 a 35 anos       Superior         b
14       F  d - 46 a 55 anos    Fundamental         b
15       M  b - 26 a 35 anos    Fundamental         b
16       F  d - 46 a 55 anos       Superior         a
17       M  b - 26 a 35 anos    Fundamental         b
18       M  e - Mais 56 anos    Fundamental         b
19       F  b - 26 a 35 anos    Fundamental         a
20       F  b - 26 a 35 anos          Medio         a
21       M  b - 26 a 35 anos          Medio         b
22       M  a - Ate 25 anos           Medio         b
23       F  e - Mais 56 anos    Fundamental         b
24       M  a - Ate 25 anos     Fundamental         b
25       F  c - 36 a 45 anos          Medio         b
26       F  b - 26 a 35 anos          Medio         b
27       M  e - Mais 56 anos    Fundamental         c
28       F  b - 26 a 35 anos    Fundamental         b
29       F  b - 26 a 35 anos          Medio         b
..     ...               ...            ...       ...
970      M  b - 26 a 35 anos       Superior         a
971      M  d - 46 a 55 anos          Medio         d
972      M  e - Mais 56 anos          Medio         a
973      F  a - Ate 25 anos           Medio         a
974      F  c - 36 a 45 anos          Medio         b
975      F  c - 36 a 45 anos          Medio         d
976      M  e - Mais 56 anos    Fundamental         c
977      M  b - 26 a 35 anos          Medio         a
978      M  b - 26 a 35 anos    Fundamental         b
979      M  c - 36 a 45 anos          Medio         a
980      F  b - 26 a 35 anos    Fundamental         b
981      F  d - 46 a 55 anos    Fundamental         a
982      M  d - 46 a 55 anos          Medio         e
983      M  a - Ate 25 anos        Superior         c
984      F  b - 26 a 35 anos          Medio         a
985      F  e - Mais 56 anos    Fundamental         a
986      M  e - Mais 56 anos    Fundamental         b
987      F  d - 46 a 55 anos       Superior         a
988      F  b - 26 a 35 anos          Medio         a
989      F  c - 36 a 45 anos    Fundamental         a
990      F  b - 26 a 35 anos          Medio         a
991      F  b - 26 a 35 anos  Pos-graduacao         b
992      F  c - 36 a 45 anos    Fundamental         b
993      F  a - Ate 25 anos           Medio         b
994      M  c - 36 a 45 anos          Medio         a
995      F  a - Ate 25 anos        Superior         a
996      F  c - 36 a 45 anos    Fundamental         d
997      M  b - 26 a 35 anos          Medio         b
998      M  b - 26 a 35 anos    Fundamental         a
999      F  b - 26 a 35 anos          Medio         c

[1000 rows x 4 columns]

In [58]:
def preprocess_features(X):
    ''' Preprocesses the student data and converts non-numeric binary variables into
        binary (0/1) variables. Converts categorical variables into dummy variables. '''
    
    # Initialize new output DataFrame
    output = pd.DataFrame(index = X.index)

    # Investigate each feature column for the data
    for col, col_data in X.iteritems():
        
        # If data type is non-numeric, replace all yes/no values with 1/0
        if col_data.dtype == object:
            col_data = col_data.replace(['yes', 'no'], [1, 0])

        # If data type is categorical, convert to dummy variables
        if col_data.dtype == object:
            # Example: 'school' => 'school_GP' and 'school_MS'
            col_data = pd.get_dummies(col_data, prefix = col)  
        
        # Collect the revised columns
        output = output.join(col_data)
    
    return output

X_all = preprocess_features(x)
print ("Processed feature columns ({} total features):\n{}".format(len(X_all.columns), list(X_all.columns)))

Processed feature columns (16 total features):
['Genero_F', 'Genero_M', 'Idade_a - Ate 25 anos ', 'Idade_b - 26 a 35 anos', 'Idade_c - 36 a 45 anos', 'Idade_d - 46 a 55 anos', 'Idade_e - Mais 56 anos', 'Escolaridade_Fundamental', 'Escolaridade_Medio', 'Escolaridade_Pos-graduacao', 'Escolaridade_Superior', 'Profissao_a', 'Profissao_b', 'Profissao_c', 'Profissao_d', 'Profissao_e']

In [59]:
X_all.head()

,Genero_F,Genero_M,Idade_a - Ate 25 anos,Idade_b - 26 a 35 anos,Idade_c - 36 a 45 anos,Idade_d - 46 a 55 anos,Idade_e - Mais 56 anos,Escolaridade_Fundamental,Escolaridade_Medio,Escolaridade_Pos-graduacao,Escolaridade_Superior,Profissao_a,Profissao_b,Profissao_c,Profissao_d,Profissao_e
0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0
1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0
2,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0
3,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0
4,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = X_all[:500], X_all[500:], y[:500].ravel(),y[500:].ravel()

In [75]:
X_train.head()

,Genero_F,Genero_M,Idade_a - Ate 25 anos,Idade_b - 26 a 35 anos,Idade_c - 36 a 45 anos,Idade_d - 46 a 55 anos,Idade_e - Mais 56 anos,Escolaridade_Fundamental,Escolaridade_Medio,Escolaridade_Pos-graduacao,Escolaridade_Superior,Profissao_a,Profissao_b,Profissao_c,Profissao_d,Profissao_e
0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0
1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0
2,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0
3,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0
4,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0

In [81]:
from sklearn.naive_bayes import GaussianNB

In [84]:
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB(priors=None)

In [87]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, clf.predict(X_train))

0.60399999999999998

In [88]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, clf.predict(X_test))

0.54600000000000004

Módulo 2 – Classificação - Questão 4
Considerando os dados presentes no arquivo classificacao_Q4.csv, treine o algoritmo k-Nearest Neighbors (KNN com k=15 e distância Euclidiana) utilizando a metodologia de validação cruzada k-fold com 10 folds não estratificados. Considere que a primeira pasta de validação seja formada pelas primeiras 10% linhas do arquivo, que a segunda pasta de validação seja formada pelas 10% linhas seguintes, e assim por diante, até atingir a última pasta, formada pelas 10% linhas finais da base.
Qual o valor médio da acurácia para as bases de validação?

In [90]:
df_classificacao_Q4=pd.read_csv('raw_data/classificacao_Q4.csv')

In [93]:
df_classificacao_Q4.shape

(1500, 101)

In [103]:
x=df_classificacao_Q4.loc[:, df_classificacao_Q4.columns != 'target']

In [104]:
y=df_classificacao_Q4.loc[:, df_classificacao_Q4.columns == 'target']

In [113]:
y.loc[[1499]]

      target
1499     1.0

In [106]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=15)

In [107]:
from sklearn.model_selection import KFold

In [108]:
kf = KFold(n_splits=10)

In [114]:
acc=[]

for train_index, test_index in kf.split(x):
    neigh=KNeighborsClassifier(n_neighbors=15)
    neigh.fit(x.loc[train_index],y.loc[train_index])
    acc.append(accuracy_score(y.loc[test_index],neigh.predict(x.loc[test_index])))
    
acc

/Users/JR/anaconda3/envs/pyfinance/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """

[0.68666666666666665,
 0.66000000000000003,
 0.62,
 0.65333333333333332,
 0.64666666666666661,
 0.66666666666666663,
 0.64666666666666661,
 0.65333333333333332,
 0.68000000000000005,
 0.60666666666666669]

In [117]:
sum(acc)/len(acc)

0.65199999999999991

Tempo restante: 01:11:53

Módulo 3 – Regressão - Questão 6
Considerando os dados do arquivo regressao_Q6.csv, treine um modelo de regressão linear com regularização L2 (RIDGE com parâmetro de regularização igual a 1.7) utilizando a metodologia de validação cruzada Leave-One-out.

Qual o valor médio do Root Mean Squared Error (RMSE) para as bases de treino?
Qual o valor médio do RMSE para as bases de validação?

In [118]:
df_regressao_Q6=pd.read_csv('raw_data/regressao_Q6.csv')

In [119]:
from sklearn.linear_model import Ridge

In [120]:
x=df_regressao_Q6.loc[:, df_regressao_Q6.columns != 'target']

In [122]:
y=df_regressao_Q6.loc[:, df_regressao_Q6.columns == 'target']

In [128]:
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_squared_error
loo = LeaveOneOut()
train_acc=[]
test_acc=[]

for train_index, test_index in loo.split(x):
    ridge=Ridge(alpha=1.7)
    ridge.fit(x.loc[train_index],y.loc[train_index])
    test_acc.append(mean_squared_error(y.loc[test_index],ridge.predict(x.loc[test_index])))
    train_acc.append(mean_squared_error(y.loc[train_index],ridge.predict(x.loc[train_index])))

train_acc

[753.19193506261206,
 753.19215039733251,
 750.55875166515239,
 751.59270991714402,
 752.04711276338969,
 753.1614650309167,
 753.0840177045593,
 750.83676103996311,
 753.18205820611297,
 753.09413640604635,
 752.11662761156424,
 751.68528126851822,
 752.86352854320478,
 752.88519773506482,
 753.19129474711031,
 752.9693528978579,
 753.16167580416004,
 753.13385449063503,
 752.53986726475409,
 753.18388489271206,
 752.32457194079927,
 751.24581236082975,
 751.09749345237105,
 752.90060598919229,
 753.02042515566961,
 753.19044834058525,
 753.11515191618889,
 752.63348509341427,
 750.54849778384971,
 752.69262560603374,
 752.13029677427801,
 752.68520441704072,
 752.90319906541674,
 751.55196403980051,
 753.11862410171557,
 753.1715999766235,
 746.08569899903989,
 751.87131666615528,
 750.93785584903117,
 749.43723749946321,
 752.85209388221608,
 752.71608998555052,
 753.16852752687817,
 753.07819555260164,
 752.77386948856201,
 753.05174599485247,
 751.31359137276331,
 752.48273307115539,
 752.87315421567223,
 753.10494562477447,
 753.19214637830282,
 749.39698018061222,
 751.42190864686609,
 751.5096943053602,
 750.92964134605438,
 752.53112060260264,
 753.17468457500843,
 752.43551313297257,
 753.18894072346154,
 752.86913647413041,
 752.95607296052219,
 752.92777135611061,
 753.17656952422738,
 753.16426583283612,
 752.62468281269832,
 752.92379642585274,
 752.73595189419109,
 753.1598339119048,
 752.0896644434805,
 752.61510589372517,
 753.02924955326887,
 752.84039984568346,
 752.63856119980778,
 753.17193713135623,
 752.00113978303625,
 753.18612697754702,
 753.15527251324897,
 752.92448483245153,
 753.10196833032421,
 753.0859862867859,
 752.82018543475056,
 753.10734670510192,
 752.67050802600727,
 752.82822113306884,
 752.87902163997683,
 753.18563199232699,
 752.98943423879928,
 753.08696154690767,
 748.1746462093821,
 752.96514182079727,
 753.14386395074075,
 753.19225286840663,
 752.04197934433432,
 753.19185700602088,
 752.63727530141114,
 752.4060269475716,
 752.98618038913173,
 753.10390028356233,
 753.09135178532586,
 752.34736605253306,
 753.16464716172879,
 753.1825945959032,
 752.24639009456052,
 753.06105750788993,
 752.90371371072013,
 752.86818668926992,
 751.45264785074448,
 752.02230851522609,
 751.32433815830746,
 753.16580003129616,
 753.04958632244291,
 752.71315198177854,
 752.97345925494676,
 752.81623673411195,
 752.98368791366499,
 751.61171616578849,
 753.07960697502915,
 753.12518228082365,
 753.17221685209245,
 752.91069041778451,
 753.09115560852081,
 752.71557250882267,
 752.72020210840037,
 751.08543695938511,
 753.08494620032104,
 753.09217233874131,
 751.29359206309755,
 753.0827047605153,
 753.10685397590794,
 753.18652965556771,
 752.30589111344136,
 752.89171176792331,
 753.18976455315294,
 752.45711099063033,
 753.17101866030157,
 752.9992006358425,
 753.18688479531295,
 748.71742294895535,
 752.81648215134817,
 752.72163989079127,
 753.1483696050642,
 753.1912147805258,
 752.90832640765063,
 752.76839454713433,
 752.98021016378607,
 751.83972539328727,
 752.41768645739467,
 753.15532367019057,
 752.40452075015514,
 751.42645028224331,
 750.8628626011473,
 753.19122116942322,
 753.05682187357127,
 752.39911219796249,
 752.39943498449838,
 752.51879912371942,
 753.17405812792754,
 752.6432283604247,
 751.24553102564244,
 753.08378914441846,
 751.72021799404581,
 751.63697055796604,
 750.84589208367845,
 753.18507043833256,
 753.0311477166681,
 748.38466933839004,
 753.05700324463328,
 752.87270153707311,
 751.31326667383257,
 750.99913032878203,
 753.03408354412329,
 752.88433625767323,
 752.47952652647518,
 752.96669779067781,
 753.16350310321764,
 753.03809583675138,
 752.3700390619266,
 752.4997673170152,
 750.80881277724416,
 752.59440487267443,
 752.69702712866649,
 752.10862355757229,
 752.71116376732652,
 752.64762645561075,
 752.98079063707507,
 752.26139788607725,
 753.0112160590827,
 752.98287177009479,
 753.05799639780469,
 752.08738120790269,
 751.73351677838946,
 753.06949191181889,
 753.02473707063211,
 751.50305153779084,
 752.93620184877147,
 753.0953188666773,
 751.47314095101422,
 752.92437321581758,
 753.16074924382667,
 749.73543818242888,
 753.13218067782464,
 752.88891470816657,
 752.52917220326049,
 752.74125405995608,
 753.14555944956271,
 752.48951760872853,
 751.65679785638656,
 752.15151113140939,
 753.02008894852725,
 753.17422766236075,
 753.03570392247821,
 752.97776173682826,
 749.62009767481732,
 752.99837680673875,
 752.74633893621103,
 752.73387940048303,
 753.16290918158938,
 752.75093751325505,
 753.19218320052289,
 751.72950325721047,
 750.71613834895822,
 753.18943824154201,
 753.18950645959717,
 752.854802223869,
 753.02864494097048,
 752.88607279479243,
 752.89081978739102,
 753.18158495312548,
 752.78253642441166,
 752.45237664791568,
 752.4708500853867,
 752.70322158983413,
 752.16449371963586,
 752.61273053649268,
 752.9762076924336,
 753.16622841461594,
 752.95756838804755,
 753.18507579962181,
 752.98941898053363,
 752.01644181620691,
 753.14786213974378,
 753.1686347067108,
 753.19007447230638,
 752.90684443132682,
 753.19016274765568,
 752.2619838175907,
 752.38614341061088,
 753.00660063296391,
 753.14712529120288,
 751.87211580040059,
 753.0397847501149,
 753.15592989639606,
 752.40412452960845,
 752.61038341318761,
 752.40303710649346,
 752.9676407595183,
 752.90625053858776,
 753.15317678999952,
 752.07872504392924,
 752.74028532869499,
 753.19152555838264,
 753.10851691064147,
 753.19134639279309,
 753.18696245742262,
 752.65402646717621,
 752.65822536168537,
 752.3886712534246,
 752.82918126555683,
 753.17823596216033,
 753.13129190138784,
 752.99657564759775,
 752.54490150439142,
 753.1855362701383,
 752.92901981870318,
 752.2963081307638,
 753.0721118850463,
 753.060200782126,
 751.92720385790369,
 752.33357692007951,
 751.1018314196217,
 751.50995650727998,
 753.19178405364073,
 752.92092755963643,
 751.4633249889456,
 752.58450856215973,
 751.92963942776521,
 753.16958857206623,
 751.19567461856445,
 752.92337661052522,
 752.9262395984241,
 752.93751813280608,
 753.19221402312451,
 752.76893672634981,
 750.96465049337519,
 752.25502230974064,
 751.43868211921449,
 753.16405241694974,
 751.87063641670147,
 753.14596589849566,
 751.9750038354,
 752.2360280507113,
 752.56872527649796,
 753.09333037745614,
 752.8414228968312,
 753.08312961510433,
 752.27503664942378,
 751.84347111182979,
 753.15201549749929,
 751.54376027356977,
 753.18143449420461,
 753.18603309299556,
 753.19224598490041,
 753.17953141908879,
 752.79399008369285,
 753.17755065874383,
 751.83433382015858,
 751.67452703700326,
 751.56417423433447,
 753.03937102603584,
 751.39684178289747,
 751.93272190281289,
 751.07916719295292,
 750.68568396102432,
 753.02890987564354,
 753.17110122851579,
 752.60266221112943,
 753.15664704869232,
 752.52142931638764,
 753.14411149919658,
 751.99689082388227,
 753.18218523656731,
 753.16950872692644,
 753.19117018881593,
 752.20585183964386,
 753.18241793885738,
 750.77534861708045,
 752.96228762521991,
 753.02153634941112,
 752.55327035771597,
 753.14285774992152,
 752.66491987772656,
 752.58064398689919,
 753.17682055437706,
 753.06901720631083,
 753.18676317354561,
 752.93312348581446,
 753.1316471815361,
 752.84346773604284,
 753.19122489239783,
 751.64962547976427,
 753.15194885143194,
 752.36446372765772,
 752.63523583084145,
 752.62888213770771,
 753.18426842673398,
 752.9338644845792,
 753.18884172410003,
 752.47666621582812,
 752.24438675320937,
 752.1192373073543,
 753.10377517204574,
 753.18589060459715,
 752.98537930384384,
 753.17423637470131,
 752.88670830569151,
 751.47200511451626,
 750.44370298201045,
 753.16996264448574,
 753.19225155091249,
 752.64152977176946,
 753.18265496737092,
 752.64083401394191,
 753.13254306356509,
 753.18880382096586,
 751.99200975645215,
 753.16229483795109,
 752.76085361273874,
 752.6840659176446,
 752.81874909533735,
 753.19070231792034,
 752.40011137119325,
 753.03739235620571,
 753.05815405227725,
 752.95784654358749,
 751.89902874747429,
 753.17726329308596,
 752.13962304381266,
 753.19068448808332,
 753.18621858432778,
 752.49041910887206,
 752.64044993991979,
 752.61844079361083,
 752.77214949490178,
 750.07936821005694,
 752.90016660121353,
 753.12348016861358,
 753.18075107650441,
 752.33925028476165,
 752.31777875162243,
 751.52618201354471,
 752.99792649649851,
 752.74049313222304,
 753.05711211036191,
 752.75531813271266,
 753.15040813820747,
 751.62209608023409,
 752.93185698998036,
 753.14029022691932,
 752.50658986180451,
 753.02684924854941,
 749.91528191939824,
 753.16053309471556,
 752.99823535475423,
 753.17513587270025,
 752.77162846972408,
 752.97110553210803,
 751.79911450278098,
 749.74445151637008,
 752.28095830810696,
 752.83475941522795,
 753.12743114060117,
 750.04093897942766,
 751.92892697318734,
 752.72492687289855,
 753.18848296076158,
 753.18558329606174,
 752.80119725497082,
 751.47202060873133,
 752.9816851175658,
 753.18977983928016,
 751.97999510659224,
 750.76007072277753,
 751.82896308497391,
 752.13976286786612,
 752.25292499544298,
 753.12494555493799,
 752.91511298225112,
 751.91631563044803,
 752.68127610352019,
 753.16770907774344,
 749.92554012109315,
 752.84828855406749,
 752.94918828623008,
 752.75999858802243,
 752.85186616751616,
 752.93058469055836,
 752.86279371945091,
 752.7355225284025,
 753.12660492185375,
 753.1869005769704,
 752.2965721801653,
 753.12203660810599,
 753.05803606590689,
 751.11153059464505,
 751.08729635111968,
 753.06425156727005,
 753.15783982841788,
 752.40730910705872,
 753.19007358507201,
 749.88880672223172,
 752.63178192510679,
 753.19075654366816,
 750.84478160088986,
 753.14267361992415,
 753.19095973327126,
 750.76042372136362,
 753.19072752277918,
 752.70485101778991,
 753.09526782368494,
 753.0748159972369,
 752.85394914734059,
 753.18601501406363,
 752.79198471212305,
 752.73772005738374,
 753.13464015052546,
 752.67331815574335,
 753.16945823041544,
 752.76412414330662,
 752.7207090798106,
 751.86849675663836,
 753.15228248286348,
 752.71214076504918,
 751.18493321339713,
 751.53713459843198,
 752.03367508947633,
 753.17737701343174,
 752.39092451384829,
 750.60123236463392,
 752.2205410311434,
 753.18477608946876,
 747.06652190380487,
 752.887615959713,
 753.16956843038633,
 752.70109886217506,
 751.67349257504168,
 752.66130178955018,
 753.07138718880424,
 752.46523512462966,
 753.07444014564624,
 752.28002038235934,
 753.18624300151066,
 752.04511965811002,
 752.09089172631116,
 752.92232397954967,
 753.04517839645689,
 750.94440332363092,
 752.8272486392018,
 753.14956246344423,
 752.97787013866332,
 751.98729910036559,
 753.17280170399727,
 749.23654307998174,
 753.18629826396307,
 752.96965298593614,
 752.26460962596423,
 753.09854006945318,
 752.68439776719958,
 753.18909713601442,
 753.19086288934693,
 752.44118531609445,
 752.3595620454679,
 750.37358362939324,
 752.73473065295741,
 752.85536691672655,
 753.13079139109925,
 752.15943961337678,
 753.04333924098694,
 753.19231240327122,
 752.98452292534137,
 753.19195518760648,
 752.93832526771962,
 752.85299600713643,
 748.71319785290689,
 752.75112037927897,
 751.26695776713768,
 753.04103366372954,
 753.11253298331826,
 751.90394551692293,
 752.96202751665624,
 748.99377931174558,
 752.59768725589606,
 753.16705902955141,
 750.8913518536549,
 752.28756587786347,
 752.97088454837308,
 753.17288353854451,
 752.86639718925937,
 753.03845409247265,
 752.89731868303636,
 752.56846838081117,
 753.04693362751811,
 752.76581292379626,
 751.66469809027649,
 753.11662968720759,
 750.54223775023638,
 753.16808783270574,
 753.17191927690931,
 753.0886123647889,
 752.96675518825816,
 753.19017533876183,
 752.67433036222292,
 752.46489730048813,
 752.95733539901801,
 752.83995215764321,
 752.50681502810687,
 752.49016033254998,
 749.58713258506589,
 753.15443265516217,
 752.96539634354986,
 750.46501357722218,
 753.06279733877398,
 752.66386309017605,
 753.12927877226764,
 753.00706094410612,
 751.34957796876643,
 752.90781001639266,
 752.98606655780554,
 753.08142581161621,
 753.16479602721824,
 752.11268106709383,
 752.33206652607828,
 752.19309790190482,
 753.08318163481647,
 753.16500996171658,
 752.65044363280776,
 752.27701406822507,
 753.17400021460503,
 752.21394821205399,
 752.51519991797545,
 752.71536578473501,
 752.85036322339647,
 753.17300002723857,
 748.93633389355057,
 751.45725031534755,
 752.69229115320206,
 753.19034927103689,
 753.17830355666251,
 752.47378762295386,
 752.00780353788036,
 753.10965034330525,
 753.09130284088917,
 753.16094876464808,
 752.92881117321951,
 752.34192264404874,
 751.85057423190972,
 753.18513547261205,
 753.18758049441249,
 753.1658411518099,
 753.19157401700693,
 753.18357682756186,
 752.58895082111496,
 751.47004147153052,
 753.19069730675562,
 748.81095088462109,
 752.78327314470812,
 751.79064943171318,
 751.75273479743112,
 751.27094024516816,
 751.85610085037399,
 753.16902603142626,
 747.15310845590443,
 752.95292520601015,
 753.07226254749776,
 753.16547306827329,
 753.18545360355517,
 751.66902069645244,
 752.88620378064195,
 753.07375573931529,
 751.62124807739792,
 752.13356920530009,
 752.32528729842272,
 753.07178708446975,
 750.50797495534584,
 753.16792103955231,
 752.78953492851394,
 753.09649420568439,
 752.79474469777608,
 752.75617016966623,
 753.1786872893116,
 751.77568684923324,
 752.6681992135924,
 752.51635269494693,
 753.03548724837526,
 753.17178695310645,
 753.16507261566562,
 752.68468375969064,
 753.13366848317332,
 749.32666643036885,
 752.64778143700448,
 751.78489137555209,
 753.02539440534156,
 751.24685369733504,
 753.0519855703576,
 753.08719043517544,
 753.1131983121702,
 752.89049575767388,
 749.65177613532501,
 749.77561707173879,
 751.03812419019118,
 751.01921995770397,
 752.86378810268616,
 753.17831889221247,
 750.25385162952227,
 749.99826331579152,
 749.99646172996745,
 752.89983594275986,
 753.07733229225607,
 752.76428331038665,
 753.0892696426879,
 753.03090881921503,
 753.16817052305134,
 753.19213031211984,
 753.18503838350614,
 753.18840315248701,
 751.64307541072412,
 753.17360234482271,
 753.18500524111471,
 752.28320121444995,
 753.19090510143201,
 751.90724874559601,
 750.18459989440487,
 751.57516992305705,
 752.92594148268734,
 753.18617341003301,
 752.59070062518526,
 752.71783980015789,
 753.06638718535896,
 747.59982702525599,
 750.81404992218086,
 750.74006230447651,
 753.0664781469967,
 753.16678869322789,
 752.96738907837812,
 752.02016079986493,
 753.04277085084857,
 753.10051413648068,
 752.85689856481679,
 753.1224444956124,
 750.25929879870523,
 752.71599919507423,
 753.19191366658458,
 752.82303225641942,
 753.02977010697077,
 751.4137814088524,
 753.17259985158296,
 752.47245264220453,
 753.03205941972556,
 751.99849195890056,
 753.0845603497969,
 751.61403787504798,
 753.19165157887778,
 752.84206816988274,
 753.13391957035367,
 753.18798189832523,
 753.19213512839235,
 752.22462712210927,
 752.14300861802985,
 752.90856276157854,
 752.61624436490149,
 752.43987566845749,
 753.06030799358655,
 752.45905382388855,
 753.19065657951217,
 752.95185323210512,
 748.74282391771453,
 749.97798775420699,
 752.77340954413944,
 753.19143407717866,
 749.07847628624961,
 753.04053896607195,
 753.18016994963375,
 752.15984786616241,
 752.75147141315279,
 750.50581477334765,
 750.34900407812142,
 753.19220210103924,
 752.54058895037213,
 752.64708913086827,
 752.61047366104958,
 753.06874194671764,
 752.79882840371545,
 750.38289887831536,
 752.76591323792923,
 752.9730430961298,
 752.14203319175078,
 751.85859785875539,
 753.04105353206808,
 753.18580529896531,
 751.21111022865341,
 753.16256444086514,
 753.08734568244768,
 753.1921293344202,
 753.1323544004556,
 752.55792729395989,
 753.04749479606357,
 753.02639831360193,
 751.03192125990483,
 752.0747443941641,
 753.01336518559106,
 753.1707622638861,
 752.78587823877535,
 753.08099753392321,
 753.02513890999978,
 752.53981987764507,
 752.13537765864521,
 752.5939318133976,
 753.1906404338639,
 752.52836615188187,
 751.85641977894261,
 753.17792061534669,
 752.38222836089074,
 752.44755707841148,
 753.11312874279531,
 750.62809163332213,
 753.18665115639953,
 752.84230901072146,
 752.53541678050874,
 750.78651022910674,
 752.06529551874792,
 753.01677398413699,
 751.58708026287911,
 753.08629309373089,
 753.14800061399183,
 751.69151967372181,
 752.52814307753943,
 752.41937276754811,
 752.80205760473802,
 752.44566199346286,
 753.18542207469864,
 753.02703136405273,
 753.05209929764067,
 751.05987501266077,
 753.19222379246037,
 752.03975917408422,
 753.07868654489062,
 753.1470893936895,
 749.54368674603097,
 753.07368077375486,
 753.19227332339369,
 753.19146967220183,
 753.18794459188109,
 752.54402219356268,
 753.11952431908139,
 753.14961512116611,
 751.46405261090763,
 752.32932124284753,
 753.19202409709158,
 752.69964520553822,
 752.84942966629899,
 753.04424184833567,
 752.92690037610078,
 753.18996465245993,
 752.15772774930974,
 752.80849413838325,
 753.18102192435197,
 751.80342746146812,
 750.58306716085144,
 753.18882716375947,
 753.06753633011704,
 752.41487791949646,
 752.74519644081624,
 753.17647715054409,
 753.12381204900714,
 751.74419788818818,
 753.06746746823694,
 753.15770209307004,
 752.34366314769511,
 752.25069839838704,
 751.51830709342153,
 753.16884865717066,
 752.89430470446052,
 752.41604221882551,
 751.97458467112961,
 750.63979130896405,
 753.04965220055306,
 752.98537481101243,
 753.07603972115669,
 752.85777779694479,
 753.09265190880092,
 752.76682204906353,
 752.40179884749546,
 752.43367396236476,
 751.85733362443818,
 752.99971116940537,
 753.19067666762544,
 752.94830404199843,
 751.46423289759377,
 752.34264715984079,
 752.76372977389474,
 753.11367427411722,
 753.11515452030255,
 753.17781476983623,
 753.0412598378324,
 753.05181870189426,
 750.17621439687116,
 753.11516765447846,
 752.17429142094898,
 750.31810692766021,
 751.59291361791827,
 752.14504889321404,
 752.99751454605143,
 752.79871187916854,
 753.16253516997153,
 751.16082850572343,
 752.61323094032377,
 752.82458881241462,
 750.22250931154008,
 752.85960819451452,
 752.34597087935151,
 749.14846423781307,
 752.15995630770169,
 751.35832098531353,
 753.19227916516593,
 753.03179309554264,
 751.40639814913334,
 753.08919936341078,
 752.38806129095053,
 752.7348299112216,
 751.31996528506943,
 752.96416992782531,
 752.16894204090261,
 753.15548445311913,
 753.07596913048042,
 752.93395212406449,
 745.7599451549662,
 753.03246409786459,
 752.83418889205905,
 752.75932536958408,
 752.93214471711588,
 753.17939212641863,
 753.11737386235427,
 753.18558604960049,
 751.71660069630093,
 753.07001390229652,
 752.60635227768103,
 751.47860905048151,
 753.17483998588909,
 753.19223237872268,
 752.05236887554759,
 751.59990735537565,
 753.18884410171381,
 752.7148938890715,
 752.73932339364296,
 752.29125351754737,
 753.01767283873835,
 753.08557048976593,
 753.1516302392248,
 749.40100204738644,
 753.15778965120296,
 752.57330875605362,
 752.96185189387847,
 752.44590374784741,
 752.60867162156183,
 753.14809097449631,
 753.15399297078511,
 753.15609854461036,
 752.46566701636334,
 753.13652770942156,
 753.0651084999987,
 752.85875109151266,
 753.14181935177976,
 753.14254768659373,
 751.57837108464821,
 752.87383804429817,
 751.40561523455244,
 752.8981214852331,
 753.12707292216658,
 752.73993819159978,
 752.50868857024182,
 752.2515261648914,
 748.34550846791831,
 753.13722770726065,
 753.18826829886052,
 752.70462508638934,
 748.90555931480753,
 753.09936789502444,
 753.12899772842707,
 751.09829788338891,
 752.66949797681741,
 752.36649487094292,
 752.97424744234399,
 753.0291571225863,
 753.12314594424356,
 752.14293759635541,
 752.02949225697034,
 753.18985873056613,
 752.72473347311234,
 753.17979524698728,
 751.08533509051915,
 752.62220860026525,
 753.12929963169711,
 753.1905055145802,
 753.01821240817992,
 753.14875110931303,
 752.82189870992624,
 753.09289769699978,

In [129]:
sum(train_acc)/len(train_acc)

752.50078132808119

In [130]:
sum(test_index)/len(test_index)

1099.0

Módulo 3 – Regressão - Questão 7
Considerando os dados do arquivo regressao_Q7.csv, treine uma árvore de regressão sem realizar nenhuma poda com quebras baseadas no erro quadrático médio (Mean Squared Error) e utilize a metodologia de validação cruzada k-fold com k = 10. 
Qual o erro absoluto médio (Mean Absolute Error) para as bases de treino?
Qual o MAE para as bases de validação?

In [132]:
df_regressao_Q7=pd.read_csv('raw_data/regressao_Q7.csv')

In [134]:
x=df_regressao_Q7.loc[:, df_regressao_Q6.columns != 'target']

In [135]:
y=df_regressao_Q7.loc[:, df_regressao_Q6.columns == 'target']

In [146]:
from sklearn.tree import DecisionTreeRegressor

In [147]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error
kfold = KFold(n_splits=10)
train_acc=[]
test_acc=[]

for train_index, test_index in kfold.split(x):
    tree=DecisionTreeRegressor()
    tree.fit(x.loc[train_index],y.loc[train_index])
    test_acc.append(mean_absolute_error(y.loc[test_index],tree.predict(x.loc[test_index])))
    train_acc.append(mean_absolute_error(y.loc[train_index],tree.predict(x.loc[train_index])))

In [148]:
sum(train_acc)/len(train_acc)

1.000536448557958e-06

In [149]:
sum(test_index)/len(test_index)

1899.5